apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: test
spec:
  template:
    spec:
      containers:
        - name: test
          resources:
            requests:
              memory: 1Mi
